# Generated by Django 6.1.1 on 2026-09-22 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('F', 'Finance'), ('HR', 'HR'), ('Ink', 'Ink Store'), ('It', 'IT'), ('Maintain', 'Maintenance'), ('Product', 'Production'), ('Sales', 'Sales'), ('Store', 'Store')], default='IT', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='admin@example.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True),
        ),
    ]
