# Generated by Django 6.1.1 on 2026-09-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_question_option_response_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updated_password',
        ),
    ]
