# Generated by Django 6.1.1 on 2026-09-24 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_user_updated_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='access_type',
            field=models.CharField(choices=[('anyone', 'Anyone with the link'), ('restricted', 'Restricted')], default='anyone', max_length=20),
        ),
        migrations.CreateModel(
            name='FormInvite',
            fields=[
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='forms.form')),
            ],
            options={
                'unique_together': {('form', 'email')},
            },
        ),
    ]
