# Generated by Django 6.1.1 on 2026-09-25 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_form_access_type_forminvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormElement',
            fields=[
                ('element_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('element_type', models.CharField(choices=[('question', 'Question'), ('text', 'Text/Description'), ('image', 'Image'), ('sec', 'Section')], max_length=20)),
                ('question_text', models.CharField(blank=True, max_length=1000)),
                ('question_type', models.CharField(blank=True, choices=[('short', 'Short answer'), ('paragraph', 'Paragraph'), ('mcq', 'Multiple choice'), ('checkbox', 'Checkboxes')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='form_images/')),
                ('is_required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='forms.form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ElementOption',
            fields=[
                ('option_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.formelement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
