# Generated by Django 6.1.1 on 2026-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_formelement_elementoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
