# Generated by Django 6.1.1 on 2026-09-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_form_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.form'),
        ),
    ]
