# Generated by Django 6.1.1 on 2026-09-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_option_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formelement',
            name='grid_rows',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formelement',
            name='max_files',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='formelement',
            name='scale_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formelement',
            name='scale_max_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='scale_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formelement',
            name='scale_min_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='question_type',
            field=models.CharField(blank=True, choices=[('short', 'Short answer'), ('paragraph', 'Paragraph'), ('mcq', 'Multiple choice'), ('checkbox', 'Checkboxes'), ('dropdown', 'Dropdown'), ('file_upload', 'File upload'), ('linear_scale', 'Linear scale'), ('mcq_grid', 'Multiple-choice grid'), ('checkbox_grid', 'Checkbox grid'), ('date', 'Date'), ('time', 'Time')], max_length=20),
        ),
    ]
