# Generated by Django 6.1.1 on 2026-09-29 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_formelement_grid_rows_formelement_max_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='file',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formelement'),
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='form_answers/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='forms.answer')),
            ],
        ),
    ]
