# Generated by Django 6.1.1 on 2026-10-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_remove_answer_file_remove_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminvite',
            name='permission',
            field=models.CharField(choices=[('respond', 'Can respond'), ('edit', 'Can edit'), ('both', 'Can edit and respond')], default='respond', max_length=10),
        ),
    ]
