# Generated by Django 6.1.1 on 2026-10-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_forminvite_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
